require("core.plugins")
require("core.mapping")
require("core.configs")
require("core.autocmd")

require("plugins.blankline")
require("plugins.hop")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.lsp_signature")
require("plugins.comments")
require("plugins.cat")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.whichkey")
require("plugins.buffline")
require("plugins.lualine")
require("plugins.cmp")
require("plugins.go")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.dashboard")

