require("core.plugins")
require("core.mapping")
require("core.configs")
require("core.autocmd")

require("plugins.formatter")
require("plugins.tailwind")
require("plugins.before")
require("plugins.neoclip")
require("plugins.project")
require("plugins.blankline")
require("plugins.hop")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.lsp_signature")
require("plugins.comments")
require("plugins.cat")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.whichkey")
require("plugins.buffline")
require("plugins.lualine")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.dashboard")
require("plugins.todo")


